<a href="https://colab.research.google.com/github/phoebelily1/block5-assessment/blob/Task-1-Joyce/1_2_intro_to_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to PyTorch as a replacement for Numpy / MATLAB

All the code in this course will be in PyTorch.  That's because PyTorch is widely agreed to be the best library for artificial intelligence/deep learning:
  * Most popular library in research
  * Battle-tested
  * Fantastic docs + tutorials + libraries than any other library
  * Pythonic and hackable: you can look at + modify the source for just about anything

PyTorch is many things.  But at its most basic, PyTorch is just a replacement for Numpy / MATLAB.  And that's how we're going to introduce PyTorch here!

Note the [PyTorch docs](https://pytorch.org/docs/stable/index.html) are great.  Learning your way around these will help alot!



In [ ]:
#Lets start by importing PyTorch
import torch as t

# Initializing PyTorch Tensors

In PyTorch, a Tensor is any numbers held by PyTorch.

So, weirdly, a Tensor could be a scalar/vector/matrix etc...

In [ ]:
#We can make a scalar one using,
scalar = t.tensor(1.)
print(f"Scalar type: {type(scalar)}")
print("Scalar value:")
print(scalar)
print()
#We can make a length 3 vector of ones using,
vector = t.ones(3)
print(f"Vector type: {type(vector)}")
print("Vector value:")
print(vector)
print()

#We can make a 3x3 matrix of ones using,
matrix = t.zeros(3,3)
print(f"Matrix type: {type(matrix)}")
print("Matrix value:")
print(matrix)


Scalar type: <class 'torch.Tensor'>
Scalar value:
tensor(1.)

Vector type: <class 'torch.Tensor'>
Vector value:
tensor([1., 1., 1.])

Matrix type: <class 'torch.Tensor'>
Matrix value:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
#But there are a bunch more ways of creating tensors,
a = t.arange(7) # 0 to n-1 (length n)
print(a)
b = t.linspace(0, 1, 4) # start, end, num-points
print(b)
c = t.eye(4) #Identity matrix
print(c)
d = t.diag(t.tensor([1, 2, 3, 4]))
print(d)
e = t.rand(4) # uniform in [0, 1]
print(e)
f = t.randn(4) # draw from Gaussian
print(f)

tensor([0, 1, 2, 3, 4, 5, 6])
tensor([0.0000, 0.3333, 0.6667, 1.0000])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]])
tensor([0.5963, 0.3302, 0.0551, 0.3806])
tensor([ 0.1413,  0.0364, -0.3708,  1.4619])


In [ ]:
#You can do all the usual arithmetic operations (elementwise) on this tensor,
a = t.arange(4)
print(a+1)
print(5*a)
print(a/2)
print(a+a)

tensor([1, 2, 3, 4])
tensor([ 0,  5, 10, 15])
tensor([0.0000, 0.5000, 1.0000, 1.5000])
tensor([0, 2, 4, 6])


# Tensor shape

90% of understanding and manipulating PyTorch Tensors comes down to manipulating tensor _shape_.

In [ ]:
#To get the shape, use tensor.shape (scalar, vector and matrix are defined above)
print(scalar.shape)
print(vector.shape)
print(matrix.shape)

torch.Size([])
torch.Size([3])
torch.Size([3, 3])


In [ ]:
#You can use these shapes to get a new Tensor of the same shape
zero_vector = t.zeros(vector.shape)
print(zero_vector)

tensor([0., 0., 0.])


In [ ]:
#A scalar could have (at least) three different shapes:
print(t.zeros(()).shape)  #A real scalar
print(t.zeros(1).shape)   #A length-1 vector
print(t.zeros(1,1).shape) #A 1x1 matrix
#You should prefer the first one unless you have good reason not to.

torch.Size([])
torch.Size([1])
torch.Size([1, 1])


In [ ]:
#A vector could have three different shapes:
print(t.zeros(3))   #A vector (could be interpreted as row or column, depending on context)
print(t.zeros(3,1)) #A column-vector, represented as a 3x1 matrix
print(t.zeros(1,3)) #A row-vector,    represented as a 1x3 matrix

tensor([0., 0., 0.])
tensor([[0.],
        [0.],
        [0.]])
tensor([[0., 0., 0.]])


## Tensor broadcasting

Sometimes you want to e.g. add a matrix to a vector.  To do this in PyTorch, we exploit "broadcasting".

In [ ]:
#You can do this
X = t.ones(3,4)
y = t.randn(4)
print(X+y)

tensor([[1.4439, 0.7797, 1.5104, 2.7050],
        [1.4439, 0.7797, 1.5104, 2.7050],
        [1.4439, 0.7797, 1.5104, 2.7050]])


In [ ]:
#But not this:
X = t.ones(3,4)
y = t.rand(3)
print(X+y)

RuntimeError: ignored

In [ ]:
#To understand what works / doesn't, we need to understand the rules of broadcasting!
#Key rule: dimensions must match, or be 1:
X = t.ones(2,3,4)
Y = t.rand(1,3,1)
#Here, the middle dimensions match.
#The first dimensions are 2 (for X) and 1 (for Y), so the Y-dimension broadcasts
#The third dimensions are 4 (for X) and 1 (for Y), so again, the Y-dimension broadcasts.
Z = X+Y
print(Z.shape)

torch.Size([2, 3, 4])


This translates into maths as:
\begin{align}
  Z_{kji} = X_{kji} + Y_j
\end{align}
(note that we only have dimension $1$ for $Y$ in the $k$ and $i$ dimensions, so its as if those indices don't exist on the Y tensor.)

We have reversed the usual order of the $i, j, k$ indices, because PyTorch actually counts backwards!

In [ ]:
#But what happens if the tensors have different numbers of dimensions?
#Here, X is a 3-dimensional tensor, while Y is a 1-dimensional tensor,
X = t.ones(2,3,4)
Y = t.ones(4)
Z = X+Y
print(Z.shape)

torch.Size([2, 3, 4])


This expression translates to math as,
\begin{align}
  Z_{kji} = X_{kji} + Y_i.
\end{align}
There are two ways to think about this:
* PyTorch counts dimensions backwards (starting from the right).
* PyTorch fills the "missing" dimensions on the left with ones.  In which case, the following code is equivalent,

In [ ]:
#Hence, the above code works just like,
X = t.ones(2,3,4)
Y = t.ones(1,1,4)
Z = X+Y
print(Z.shape)

torch.Size([2, 3, 4])


In [ ]:
#However, the following code gives an error, because
#X.shape = torch.Size([2]) behaves like Y.shape = torch.Size([1,1,2]), and
#this doesn't broadcast with X.shape = torch.Size(2,3,4)
#Because in the third dimesion, 2 != 4.
X = t.ones(2,3,4)
Y = t.rand(2)
X+Y


RuntimeError: ignored

This expression translates to math in the same way, as
\begin{align}
  Z_{kji} = X_{kji} + Y_i.
\end{align}
But now the "i" dimension on X and the "i" dimension on Y don't match, which gives an error.

In [ ]:
#The above code behaves just like,
X = t.ones(2,3,4)
Y = t.rand(1,1,2)
X+Y

RuntimeError: ignored

In [ ]:
#But what if we do want to do broadcast along the first dimension?  We need to construct Y so that the length 2 dimension appears in the right place!
X = t.ones(2,3,4)
Y = t.randn(2,1,1)
Z = X+Y
print(Z.shape)

tensor([[[1.1823, 1.1823, 1.1823, 1.1823],
         [1.1823, 1.1823, 1.1823, 1.1823],
         [1.1823, 1.1823, 1.1823, 1.1823]],

        [[0.8650, 0.8650, 0.8650, 0.8650],
         [0.8650, 0.8650, 0.8650, 0.8650],
         [0.8650, 0.8650, 0.8650, 0.8650]]])


This expression translates to math as
\begin{align}
  Z_{kji} = X_{kji} + Y_k.
\end{align}
So now the "k" dimension on X and the "k" dimension on Y do match!

In [ ]:
#But what if we already have Y that's the wrong shape?
X = t.ones(2,3,4)
Y = t.randn(2)
#Y is the wrong shape to broadcast with X!
print(Y.shape) #torch.Size([2])
#We can add extra dimensions to Y using,
Y = Y[:, None, None]
#The None's add extra 1 dimensions, we have a tensor of the right shape!
print(Y.shape) #torch.Size([2,1,1])
#And the broadcasting works,
print(X+Y)

torch.Size([2])
torch.Size([2, 1, 1])
tensor([[[2.8538, 2.8538, 2.8538, 2.8538],
         [2.8538, 2.8538, 2.8538, 2.8538],
         [2.8538, 2.8538, 2.8538, 2.8538]],

        [[0.9171, 0.9171, 0.9171, 0.9171],
         [0.9171, 0.9171, 0.9171, 0.9171],
         [0.9171, 0.9171, 0.9171, 0.9171]]])


# Additional useful operations

In [ ]:
#Matrix operations
A = t.randn((2,3))
print("Matrix")
print(A)
print("\nMatrix Transpose")
print(A.mT)
print("\nElementwise product")
print(A * A)
print("\nMatrix Product")
print(A @ A.mT)

Matrix
tensor([[ 0.6763, -1.0383,  0.0390],
        [-1.0920,  1.3589, -0.0114]])

Matrix Transpose
tensor([[ 0.6763, -1.0920],
        [-1.0383,  1.3589],
        [ 0.0390, -0.0114]])

Elementwise product
tensor([[4.5733e-01, 1.0780e+00, 1.5246e-03],
        [1.1924e+00, 1.8466e+00, 1.2914e-04]])

Matrix Product
tensor([[ 1.5369, -2.1498],
        [-2.1498,  3.0390]])


In [ ]:
#Matrix-vector operations
N = 2
M = 3
A = t.randn((M, N))
a_vec = t.randn(M)
b_vec = t.randn(N)

#Interprets a_vec as a row-vector (otherwise matrix-vector product wouldn't make sense)
#Input is a vector (with one dimension); output is a vector (with one dimension)
print((a_vec @ A).shape)
#Interprets b_vec as a column-vector (otherwise matrix-vector product wouldn't make sense)
#Input is a vector (with one dimension); output is a vector (with one dimension)
print((A @ b_vec).shape)
#We can also convert a_vec to an explicit row-vector, by converting to a matrix
#of shape 1xM
a_rowvec = a_vec[None, :]
print(a_rowvec)
#Now, input is a row-vector in matrix form (1xM), so output is a row-vector in matrix form (1xN)
print((a_rowvec @ A).shape)
#Likewise, we can convert b_vec to an explicit column-vector, by converting to a matrix
#of shape Nx1
b_colvec = b_vec[:, None]
print(b_colvec)
#Now, input is a row-vector in matrix form (Nx1), so output is a row-vector in matrix form (Mx1)
print((A @ b_colvec).shape)



torch.Size([2])
torch.Size([3])
tensor([[ 1.3393, -0.0658, -0.1073]])
torch.Size([1, 2])
tensor([[1.2998],
        [0.6548]])
torch.Size([3, 1])


In [ ]:
#One-argument operations.  Note that for most (but not all) of these operations,
#there are two ways of calling:
#* There is a function that lives in the torch package.  As we have imported torch
#  as `t`, these are e.g. t.exp().
#* Alternatively, they can be called as methods on the tensor, like x.log():
x = t.rand(3)
print("Exponential")
print(t.exp(x))
print(x.exp())
print("\n(Natural) Logarithm")
print(t.log(x))
print(x.log())
print("\nExponential")
print(t.exp(x))
print(x.exp())
print("\nSine")
print(t.sin(x))
print(x.sin())
print("\nCosine")
print(t.cos(x))
print(x.cos())
#For _loads_ more, see https://pytorch.org/docs/stable/torch.html

Exponential
tensor([1.9795, 1.1312, 1.7312])
tensor([1.9795, 1.1312, 1.7312])

(Natural) Logarithm
tensor([-0.3815, -2.0932, -0.6000])
tensor([-0.3815, -2.0932, -0.6000])

Exponential
tensor([1.9795, 1.1312, 1.7312])
tensor([1.9795, 1.1312, 1.7312])

Sine
tensor([0.6310, 0.1230, 0.5217])
tensor([0.6310, 0.1230, 0.5217])

Cosine
tensor([0.7758, 0.9924, 0.8531])
tensor([0.7758, 0.9924, 0.8531])


##Reduction operations

There are a bunch of operations (mean, sum, prod, std, var) etc.
They all do the obvious things.
But the key trick is understanding how these operations interact with Tensor shape.

In [ ]:
A = t.randn(2,3,4)

In [ ]:
#All these ops reduce over a dimension, and we need to provide an explicit index for that dimension.
print(A.mean(0).shape)
print(A.mean(1).shape)
print(A.mean(2).shape)
#We can index from the back, as in list/tuple indexing
print(A.mean(-1).shape)

torch.Size([3, 4])
torch.Size([2, 4])
torch.Size([2, 3])
torch.Size([2, 3])


`A.mean(0)` translates to math as:
\begin{align}
M_{jk} = \tfrac{1}{2} \sum_{i=1}^2 A_{ijk}
\end{align}
`A.mean(1)` translates to math as:
\begin{align}
M_{ik} = \tfrac{1}{3} \sum_{j=1}^3 A_{ijk}
\end{align}
`A.mean(2)` translates to math as:
\begin{align}
M_{ij} = \tfrac{1}{4} \sum_{k=1}^4 A_{ijk}
\end{align}

In [ ]:
#What if we want to mean-subtract A.  That's easy if we want to take the mean over the first dimension, as the shapes broadcast,
A_mean = A.mean(0)
print(f"A.shape =   {A.shape}")
print(f"A_mean.shape = {A_mean.shape}")
A-A_mean

A.shape =   torch.Size([2, 3, 4])
A_mean.shape = torch.Size([3, 4])


tensor([[[-0.0793,  0.4218,  0.2540, -0.0475],
         [-0.4991, -0.1890, -0.7578, -0.3726],
         [-1.0232,  0.5193, -1.0470, -0.1153]],

        [[ 0.0793, -0.4218, -0.2540,  0.0475],
         [ 0.4991,  0.1890,  0.7578,  0.3726],
         [ 1.0232, -0.5193,  1.0470,  0.1153]]])

In [ ]:
#But mean-subtracting A doesn't automatically work if we want to take the mean over the second or third dimension, as the resulting mean Tensor doesn't broadcast
A_mean = A.mean(2)
print(f"A.shape =   {A.shape}")
print(f"A_mean.shape = {A_mean.shape}")
A-A_mean

A.shape =   torch.Size([2, 3, 4])
A_mean.shape = torch.Size([2, 3])


RuntimeError: ignored

In [ ]:
#Looking at the docs, there's an easy way to fix this bug: use the keepdim=True kwarg,
#this keeps a single element in the final dimension, so broadcasting still works!
A_mean = A.mean(2, keepdim=True)
print(f"A.shape =      {A.shape}")
print(f"A_mean.shape = {A_mean.shape}")
A-A_mean

A.shape =      torch.Size([2, 3, 4])
A_mean.shape = torch.Size([2, 3, 1])


tensor([[[ 0.3023,  0.8004, -0.0633, -1.0394],
         [-0.2487,  0.8229, -0.3850, -0.1892],
         [-0.5236, -0.2370, -0.4020,  1.1626]],

        [[ 0.7354,  0.2314, -0.2969, -0.6699],
         [-0.1598,  0.2916,  0.2214, -0.3532],
         [ 0.6897, -2.1087,  0.8590,  0.5601]]])